apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: true
    uid: prometheus
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
        - datasourceUid: tempo
          name: traceID

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: 'trace_id[^a-f0-9]+([a-f0-9]+)'
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"
        - datasourceUid: tempo
          matcherRegex: 'traceid[^a-f0-9]+([a-f0-9]+)'
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '-1m'
        spanEndTimeShift: '1m'
        tags:
          - key: 'service.name'
            value: 'job'
          - key: 'service_name'
            value: 'job'
        filterByTraceID: true
        filterBySpanID: false
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
